<h2>{#G-credentials#}</h2>
{#message#}
<form action="{#url#}" method="post">
    <input type="hidden" name="step" value="credentials" />
    
    <p>{#credentials_desc#}</p>
    
    <div class="input">
        <p>{#username#}</p>
        <input type="text" name="username" autocomplete="off" required>
    </div>
    <div class="input">
        <p>{#password#}</p>
        <input type="password" name="password" autocomplete="off" required>
    </div>
    <br>
    <div class="input">
    	<input type="submit" name="save" value="{#save#}" />
    </div>
</form>