<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" dir="{#direction#}" lang="en-US">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset={#charset#}" />
    <meta name="robots" content="noindex,nofollow" />
    <title>{#G-title#}</title>
    <link rel='stylesheet' id='open-sans-css' href='https://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.5.3' type='text/css' media='all' />
    <link rel="stylesheet" type="text/css" href="installer/templates/css/style.css" />
    <script type='text/javascript' src='installer/templates/js/jQuery-2.1.4.min.js'></script>
</head>
<body>
    <div id="header">
		<div id="logo">
            <a href="{#home_url#}" title="{#G-title#}"></a>
        </div>
        <h1>{#G-title#}</h1>
	</div>
	<div id="body">
        <div id="content">
        {#DATA#}
        </div>
    	<div id="sidebar">
    		<h2>{#G-navigation#}</h2>
    		<ul>
                <li {#LINK1#}>{#G-index#}</li>
                <li {#LINK2#}><a href="{#home_url#}?step=credentials">{#G-credentials#}</a></li>
                <li {#LINK3#}><a href="{#home_url#}?step=general">{#G-settings#}</a></li>
                <li {#LINK4#}><a href="{#home_url#}?step=api">{#G-api_settings#}</a></li>
                <li><a href="{#home_url#}?step=logout">{#G-logout#}</a></li>
            </ul>
            <!-- <div class="lang">
                <p>{#G-choose_language#}</p>
                <select name='lang'><option value='0'>{#G-language#}</option>{#lang_options#}</select>
            </div> -->
    	</div>
        <div class="break"></div>
	</div>
    <div id="footer">
	   <p>{#G-copyright#}</p>
    </div>
</body>
</html>